FROM golang:1.24-alpine

RUN apk add --no-cache git && \
    go install github.com/air-verse/air@v1.61.5

WORKDIR /workspace

# Copy shared module
COPY shared /workspace/shared

# Copy product-service
COPY services/product-service /workspace/services/product-service

# Set working directory to product-service
WORKDIR /workspace/services/product-service

RUN go mod download

EXPOSE 8080
CMD ["air"]